### ISSUE TITLE
Cooldown problem on action bars

### ISSUE THREAD

**Issue by CptPoireau** [ElvUI-TBC/ElvUI#236] opened 2017-07-10 00:18 UTC
Hello,

It doesn't show any error but my cooldown on action bars of Consecration isn't working.

As you can see on the screenshot i just casted it. Other skills are working fine.

https://i.imgur.com/URgbOCa.jpg

**Comment by fatlus** [comment] 2017-07-10 07:29
Was fixed with https://github.com/ElvUI-TBC/ElvUI/commit/1351308213fa3363bdd347525536c8061f672735

**Comment by Bunny67** [comment] 2017-07-14 08:48
Is the problem still there?

**Comment by crumdidlyumshis** [comment] 2017-07-21 04:22
Works as intended. Closing.

**Closed by crumdidlyumshis** 2017-07-21 04:22 UTC
