### ISSUE TITLE
Aggro display on UF not working

### ISSUE THREAD

**Issue by Redtuzk** [ElvUI-TBC/ElvUI#254] opened 2017-07-14 14:17 UTC
Can't get the aggrodisplay to work anywhere, be it player, party or raid UF.
All the correct options are checked.

**Comment by Redtuzk** [comment] 2017-07-23 01:45
Any update available on this?
Really miss being able to see aggro status as a healer

**Comment by CrilleM** [comment] 2017-07-23 20:49
Same Problem, no aggrodisplay on any UF

**Comment by lishpeth** [comment] 2017-07-28 11:12
I can confirm this, none of the options like border/glow/icon works with threat display on Unit Frames.

**Comment by Tremolo4** [comment] 2017-07-31 15:21
Fixed in #272 - feel free to test.
Although @Loaal might push a different solution in the near future.

**Comment by Redtuzk** [comment] 2017-07-31 15:59
@Tremolo4 How would I practically go about adding your changes, other than copy/pasting the code in your pull request? 😄

**Comment by Redtuzk** [comment] 2017-07-31 17:42
I don't know how to use github, I only come here to submit tickets for the backport and download updates, so even googling would be hard since I don't know the correct terminology. Otherwise I obviously would have googled it.

Will download your version, thanks a lot.

**Comment by Redtuzk** [comment] 2017-07-31 17:51
@Tremolo4 So yea, had a chance to test it out -- awesome job, it works! 👍 

Only thing I can't get to work is the Icons (topleft, bottom, middle, etc). 
Glow, health border and infopanel border seems to work fine.

**Comment by Tremolo4** [comment] 2017-07-31 17:55
Cool!
I'll check out the icons when I get the chance.

Do you use Omen (or anything else with ThreatLib)? 
A possible bug I noticed is that the aggro indicator is orange even when it should be red.

Intended behaviour (only if Omen or ThreatLib is installed):
orange = aggro, but someone else has higher threat
red = aggro, and you also have highest threat

**Comment by Redtuzk** [comment] 2017-07-31 18:04
Haven't specifically noticed that, since I just tested it by pulling a mob out in the world.

**Comment by fatlus** [comment] 2017-10-03 11:22
Could this fix implemented in the main branch?

**Comment by Tremolo4** [comment] 2017-12-13 01:10
Now fixed via Plugin https://github.com/Tremolo4/ElvUI_ThreatDisplayFix

**Comment by Apollyonn** [comment] 2018-07-23 13:53
https://github.com/ElvUI-TBC/ElvUI/issues/368

**Closed by Apollyonn** 2018-07-23 13:53 UTC
