### ISSUE TITLE
Filter BuffIndicator 

### ISSUE THREAD

**Issue by mpuryear** [ElvUI-TBC/ElvUI#314] opened 2017-09-24 23:46 UTC
The toggle box "Show Aura From Other Players" doesn't toggle anything, as when the BuffIndicator gets updated it grabs all spells that the players class can cast, regardless of who cast it. I was unsure of where to fix it, but I imagine you would just add a check to see if the buff has a nil duration somewhere.

The list of class spells it uses is in ElvUI\config\filters\unitframe.lua    G.unitframe.buffwatch

Specifically the buffindicator is doing this for the raid frames. I do not use the party frames, so it may be working as intended there.

It's simple to test. Play a druid with lifebloom or rejuv, and be in a group with a second one, you can see their buffs with no duration on the frames when you have lifebloom and rejuv the "Show Aura From Other Players" unchecked.

**Comment by Slashkill** [comment] 2018-01-09 21:25
I have this issue and i would love a fix for this issue. I can't raid with 2 druids in the same raid because i can't distinguish my LB from Theirs on the same target.

**Comment by TurbanOffi** [comment] 2018-02-03 19:28
Same problem over here. Would be awesome, if someone can fix this.

**Comment by theshieldz** [comment] 2018-06-10 13:49
ye me too

**Comment by Apollyonn** [comment] 2018-08-01 05:48
Duplicate of https://github.com/ElvUI-TBC/ElvUI/issues/248

**Closed by Apollyonn** 2018-08-01 05:48 UTC
