### ISSUE TITLE
Recount sometimes not shown after a relog

### ISSUE THREAD

**Issue by fatlus** [ElvUI-TBC/ElvUI#278] opened 2017-08-01 10:40 UTC
I must toggle it with /recount toggle sometimes after a relog. Don't exactly know if this caused by ElvUI or AddonSkins. I deactivated embed settings in AddonSkins because this made another problems (check the ticket there)

**Comment by Loaal** [comment] 2017-09-16 11:27
Duplicate of ElvUI-TBC/ElvUI_AddOnSkins#11

**Closed by Loaal** 2017-09-16 11:27 UTC
