### ISSUE TITLE
[BUG] NPC Shops Color Highlighting Wrong

### ISSUE THREAD

**Issue by bwehrke** [ElvUI-TBC/ElvUI#53] opened 2017-05-15 00:48 UTC
When browsing items from NPC shops, the outline highlighting (green,blue) tends to be off sometimes. Tested with vendors such as Scryers Rep vendor in Shattrath.

**Comment by crumdidlyumshis** [comment] 2017-05-15 01:54
I was noticing this on the burning-crusade vendors but thought it was a server side issue due to maybe the devs not adding a certain tag to the npcs. I'll look into this

**Comment by crumdidlyumshis** [comment] 2017-05-15 13:03
Which server did you encounter this on? I am unable to reproduce this.

**Comment by bwehrke** [comment] 2017-05-15 14:32
Hellfire-TBC Progressive. It is currently not showing any highlighting in vendors for me, after restart the next day.

**Comment by crumdidlyumshis** [comment] 2017-06-01 02:42
Hmm, still cannot reproduce. I will keep an eye on this for the future. I have to think this is a server-side issue. Closing for now.

**Closed by crumdidlyumshis** 2017-06-01 02:42 UTC
