### ISSUE TITLE
Talents when inspecting.

### ISSUE THREAD

**Issue by TIGJERUX** [ElvUI-TBC/ElvUI#245] opened 2017-07-11 17:18 UTC
When inspecting someone you are targeting under the character and pvp tab everything is fine, but once you go under Talents tab, it now shows talents for whoever you are targeting.
https://gyazo.com/598945c8059e12577e25a3851bde335f
as you can see in the gyazo my target stays the same,
you can see my mouse going around the screen, and the talents change to whoever I am targeting.

**Comment by crumdidlyumshis** [comment] 2017-07-11 17:26
This is correct and how it should work. 🤓

**Comment by crumdidlyumshis** [comment] 2017-07-11 17:29
Oh wait your just mousover the target? Not targeting.

**Comment by TIGJERUX** [comment] 2017-07-11 17:32
Yes, you can see my unitframes stay the same, also my targets name stays the same at the very top. its just talents that change to whatever I have my mouse over. Sorry, didn't make it clear. :D

**Comment by crumdidlyumshis** [comment] 2017-07-11 17:46
Well that for sure is a bug haha. Probably easy fix. We will get it fixed :)

**Comment by Loaal** [comment] 2017-07-11 21:09
I can't reproduce. Not sure it's ElvUI bug, please share your addons list

**Comment by crumdidlyumshis** [comment] 2017-07-15 02:43
I just reproduced it too. Was inspecting a character of @Apollyonn and looked at the Talents tab while inspecting. Then just simply moused over someone and it switched talents. Confirmed.

**Comment by crumdidlyumshis** [comment] 2017-07-15 03:08
Okay, I did a bunch of tests with addons and found the culprit. GearScoreLite.

Unfortunately, this is not something we can fix. You will have to ask the original author of this addon. 

Closing.

**Closed by crumdidlyumshis** 2017-07-15 03:08 UTC
